BASE_RUN_DIR: data/results/rearrange/skills/tidy_house/nav_v1_disc_SCR
BASE_TASK_CONFIG_PATH: configs/rearrange/tasks/nav_v1.yaml
CHECKPOINT_FOLDER: data/results/rearrange/skills/tidy_house/nav_v1_disc_SCR//checkpoints
CHECKPOINT_INTERVAL: 150
CMD_TRAILING_OPTS: []
DEBUG: False
ENV_NAME: RearrangeRLEnv-v0
EVAL:
  BATCH_ENVS: False
  CKPT_PATH: 
  DETERMINISTIC_ACTION: True
  NUM_EPISODES: -1
  PREFIX: 
  SPLIT: val
FORCE_TORCH_SINGLE_THREADED: True
LOG_FILE: data/results/rearrange/skills/tidy_house/nav_v1_disc_SCR//log.train.txt
LOG_INTERVAL: 10
NUM_CHECKPOINTS: 10
NUM_ENVIRONMENTS: 64
PREFIX: 
RL:
  ACTION_NAME: BaseDiscVelAction
  IGNORE_TRUNCATED: False
  POLICY:
    CATEGORICAL_ACTOR:
      hidden_sizes: []
    CRITIC:
      hidden_sizes: []
    CRNet:
      depth_uuids: ['robot_head_depth']
      hidden_size: 512
      rgb_uuids: []
      rnn_hidden_size: 512
      state_hidden_sizes: []
      state_uuids: ['nav_goal_at_base']
    GAUSSIAN_ACTOR:
      action_activation: tanh
      conditioned_std: False
      hidden_sizes: []
      max_std: 2
      min_std: -5
      std_init_bias: 0.0
      std_transform: log
    USE_PREV_ACTIONS: True
    actor_type: categorical
    name: CRPolicy
  PPO:
    clip_param: 0.2
    entropy_coef: 0.0
    eps: 1e-05
    gamma: 0.99
    lr: 0.0003
    max_grad_norm: 0.5
    num_mini_batch: 2
    num_steps: 128
    ppo_epoch: 2
    reward_window_size: 100
    tau: 0.95
    use_clipped_value_loss: True
    use_gae: True
    use_linear_clip_decay: False
    use_linear_lr_decay: True
    use_normalized_advantage: True
    use_recurrent_generator: True
    value_loss_coef: 0.5
  REWARD_MEASURES: ['rearrange_nav_reward', 'force_penalty']
  SLACK_REWARD: -0.002
  SUCCESS_MEASURE: rearrange_nav_success
  SUCCESS_ON_STOP: True
  SUCCESS_REWARD: 2.5
SENSORS: ['HEAD_DEPTH_SENSOR']
SIMULATOR_GPU_ID: 0
SPLIT_DATASET: True
SUMMARIZE_INTERVAL: -1
TASK_CONFIG:
  DATASET:
    CONTENT_SCENES: ['*']
    DATA_PATH: data/datasets/rearrange/v3/tidy_house_220417_{split}.json.gz
    EPISODE_IDS: []
    NUM_EPISODES: -1
    SCENES_DIR: 
    SPLIT: train
    TYPE: RearrangeDataset-v0
  ENVIRONMENT:
    ITERATOR_OPTIONS:
      CYCLE: True
      GROUP_BY_SCENE: True
      MAX_SCENE_REPEAT_EPISODES: -1
      MAX_SCENE_REPEAT_STEPS: -1
      NUM_EPISODE_SAMPLE: -1
      SHUFFLE: True
      STEP_REPETITION_RANGE: 0.2
    MAX_EPISODE_SECONDS: 10000000
    MAX_EPISODE_STEPS: 500
  SEED: 100

  # 这部分定义了模拟器
  SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    AGENT_0:
      HEIGHT: 1.5
      IS_SET_START_STATE: False
      RADIUS: 0.3
      SENSORS: ['HEAD_RGB_SENSOR', 'HEAD_DEPTH_SENSOR', 'ARM_RGB_SENSOR', 'ARM_DEPTH_SENSOR', 'THIRD_RGB_SENSOR']
      START_POSITION: [0, 0, 0]
      START_ROTATION: [0, 0, 0, 1]
    ARM_DEPTH_SENSOR:
      HEIGHT: 128
      HFOV: 90
      MAX_DEPTH: 10.0
      MIN_DEPTH: 0.0
      NORMALIZE_DEPTH: True
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimDepthSensor
      UUID: robot_arm_depth
      WIDTH: 128
    ARM_RGB_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimRGBSensor
      UUID: robot_arm_rgb
      WIDTH: 128
    ARM_SEMANTIC_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimSemanticSensor
      UUID: robot_arm_semantic
      WIDTH: 128
    CONTROL_FREQ: 4
    DEFAULT_AGENT_ID: 0
    DEPTH_SENSOR:
      HEIGHT: 128
      HFOV: 90
      MAX_DEPTH: 10.0
      MIN_DEPTH: 0.0
      NORMALIZE_DEPTH: True
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimDepthSensor
      WIDTH: 128
    FETCH_ROBOT:
      PARAMS:
        
      TYPE: hab_fetch
    FORWARD_STEP_SIZE: 0.25
    HABITAT_SIM_V0:
      ALLOW_SLIDING: True
      ENABLE_PHYSICS: True
      GPU_DEVICE_ID: 0
      GPU_GPU: False
      PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    HEAD_DEPTH_SENSOR:
      HEIGHT: 128
      HFOV: 90
      MAX_DEPTH: 10.0
      MIN_DEPTH: 0.0
      NORMALIZE_DEPTH: True
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimDepthSensor
      UUID: robot_head_depth
      WIDTH: 128
    HEAD_RGB_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimRGBSensor
      UUID: robot_head_rgb
      WIDTH: 128
    HEAD_SEMANTIC_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimSemanticSensor
      UUID: robot_head_semantic
      WIDTH: 128
    RGB_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimRGBSensor
      WIDTH: 128
    SCENE: 
    SCENE_DATASET: data/replica_cad/replicaCAD.scene_dataset_config.json
    SEED: 100
    SEMANTIC_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimSemanticSensor
      WIDTH: 128
    SIM_FREQ: 120
    THIRD_DEPTH_SENSOR:
      HEIGHT: 128
      HFOV: 90
      MAX_DEPTH: 10.0
      MIN_DEPTH: 0.0
      NORMALIZE_DEPTH: True
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimDepthSensor
      UUID: robot_third_depth
      WIDTH: 128
    THIRD_RGB_SENSOR:
      HEIGHT: 512
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimRGBSensor
      UUID: robot_third_rgb
      WIDTH: 512
    THIRD_SEMANTIC_SENSOR:
      HEIGHT: 128
      HFOV: 90
      ORIENTATION: [0.0, 0.0, 0.0]
      POSITION: [0, 1.25, 0]
      SENSOR_SUBTYPE: PINHOLE
      TYPE: HabitatSimSemanticSensor
      UUID: robot_third_semantic
      WIDTH: 128
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
    VERBOSE: False
  TASK:
    ACTIONS:
      ArmGripperAction:
        ARM_ACTION:
          CTRL_SCALE: 0.015
          TYPE: ArmEEAction
        GRIPPER_ACTION:
          THRESHOLD: 0.15
          TYPE: MagicGraspAction
        TYPE: ArmGripperAction
      ArmGripperAction2:
        ARM_ACTION:
          CTRL_SCALE: 0.025
          TYPE: ArmRelPosAction
        GRIPPER_ACTION:
          THRESHOLD: 0.15
          TYPE: MagicGraspAction
        TYPE: ArmGripperAction
      BaseArmGripperAction:
        ARM_ACTION:
          CTRL_SCALE: 0.015
          TYPE: ArmEEAction
        BASE_ACTION:
          ANG_SCALE: 1.5
          LIN_SCALE: 1.5
          TYPE: BaseVelAction
          UPDATE_GRASP: True
        GRIPPER_ACTION:
          THRESHOLD: 0.15
          TYPE: MagicGraspAction
        TYPE: BaseArmGripperAction
      BaseArmGripperAction2:
        ARM_ACTION:
          CTRL_SCALE: 0.025
          TYPE: ArmRelPosAction
        BASE_ACTION:
          ANG_SCALE: 1.5
          LIN_SCALE: 1.5
          TYPE: BaseVelAction
          UPDATE_GRASP: True
        GRIPPER_ACTION:
          THRESHOLD: 0.15
          TYPE: MagicGraspAction
        TYPE: BaseArmGripperAction
      BaseDiscVelAction:
        ANG_SCALE: 3.0
        END_ON_STOP: True
        LIN_SCALE: 3.0
        TYPE: BaseDiscVelAction
        UPDATE_GRASP: True
      BaseVelAction:
        ANG_SCALE: 3.0
        LIN_SCALE: 3.0
        TYPE: BaseVelAction
        UPDATE_GRASP: True
      BaseVelAction2:
        ANG_SCALE: 3.0
        END_ON_STOP: True
        LIN_SCALE: 3.0
        TYPE: BaseVelStopAction
        UPDATE_GRASP: True
      EmptyAction:
        TYPE: EmptyAction
    AngDistanceToGoal:
      TYPE: AngDistanceToGoalV1
      UUID: ang_dist_to_nav_goal
    AngDistanceToNavGoal:
      TYPE: AngDistanceToNavGoal
    ArmJointPositionSensor:
      TYPE: ArmJointPositionSensor
    ArmJointVelocitySensor:
      TYPE: ArmJointVelocitySensor
    BaseHeadingSensor:
      EPISODIC: True
      TYPE: BaseHeadingSensor
      UUID: base_heading_at_episode
    BasePositionSensor:
      FRAME: start_base
      TYPE: BasePositionSensor
      UUID: base_pos_at_episode
    DRAWER_INIT_RANGE: [0.4, 0.5]
    FRIDGE_INIT_RANGE: [1.5, 2.35]
    ForcePenalty:
      FORCE_PENALTY: 0.001
      MAX_ACCUM_FORCE: -1.0
      MAX_ACCUM_FORCE_PENALTY: 1.0
      MAX_FORCE_PENALTY: 0.2
      TYPE: ForcePenalty
    GeoDistanceToNavGoal:
      TYPE: GeoDistanceToNavGoal
    GeoDistanceToNavGoals:
      MIN_DIST: 0.05
      TYPE: GeoDistanceToNavGoalsV1
      UUID: geo_dist_to_nav_goal
    GripperPositionSensor:
      FRAME: base
      TYPE: GripperPositionSensor
      UUID: gripper_pos_at_base
    IsGraspedSensor:
      TYPE: IsGraspedSensor
    MEASUREMENTS: ['GeoDistanceToNavGoals', 'AngDistanceToGoal', 'RearrangeNavSuccess', 'RearrangeNavReward', 'RobotForce', 'ForcePenalty']
    NavGoalSensor:
      FRAME: base
      TYPE: NavGoalSensor
      UUID: nav_goal_at_base
    POSSIBLE_ACTIONS: ['BaseVelAction', 'BaseDiscVelAction', 'BaseVelAction2']
    PickGoalSensor:
      FRAME: gripper
      TYPE: PickGoalSensor
      UUID: pick_goal_at_gripper
    PickGoalSensor2:
      FRAME: base
      TYPE: PickGoalSensor
      UUID: pick_goal_at_base
    PlaceGoalSensor:
      FRAME: gripper
      TYPE: PlaceGoalSensor
      UUID: place_goal_at_gripper
    PlaceGoalSensor2:
      FRAME: base
      TYPE: PlaceGoalSensor
      UUID: place_goal_at_base
    RearrangeNavReward:
      ANG_DIST_REWARD: 0.0
      ANG_REWARD_THRESH: -1.0
      GEO_DIST_REWARD: 1.0
      TYPE: RearrangeNavReward
    RearrangeNavSuccess:
      ANG_THRESHOLD: 0.25
      GEO_THRESHOLD: 0.1
      TYPE: RearrangeNavSuccess
    RestingPositionSensor:
      FRAME: base
      TYPE: RestingPositionSensor
      UUID: resting_pos_at_base
    RobotForce:
      INCLUDE_OBJ_COLLISIONS: True
      MIN_DELTA_FORCE: 20.0
      TYPE: RobotForce
    SENSORS: ['NavGoalSensor']
    SUB_TASKS: ['pick', 'place']
    TOP_DOWN_MAP:
      DRAW_BORDER: True
      DRAW_GOAL_AABBS: True
      DRAW_GOAL_POSITIONS: True
      DRAW_SHORTEST_PATH: True
      DRAW_SOURCE: True
      DRAW_VIEW_POINTS: True
      FOG_OF_WAR:
        DRAW: True
        FOV: 90
        VISIBILITY_DIST: 5.0
      MAP_PADDING: 3
      MAP_RESOLUTION: 1024
      MAX_EPISODE_STEPS: 1000
      TYPE: TopDownMap
    TYPE: RearrangeNavTask-v1
    USE_BAKED_SCENES: False
TENSORBOARD_DIR: data/results/rearrange/skills/tidy_house/nav_v1_disc_SCR//tb
TORCH_GPU_ID: 0
TOTAL_NUM_STEPS: 100000000.0
TRAINER_NAME: ppo-v0
VERBOSE: True
VIDEO_DIR: data/results/rearrange/skills/tidy_house/nav_v1_disc_SCR//video
VIDEO_OPTION: ['disk']