# 定义环境相关参数
ENVIRONMENT:
    # Number of steps within an episode.
    MAX_EPISODE_STEPS: 200

# 定义数据集相关参数
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    # The dataset to use. Later we will generate our own dataset.
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/nav_pick.json.gz
    SCENES_DIR: "data/replica_cad/"

# 定义任务相关参数
TASK:
    TYPE: RearrangeDemoNavPickTask-v0

    # Sensors for the observation space.
    # 上文定义
    TARGET_START_SENSOR:
        TYPE: "TargetStartSensor"
    # 定义在habitat-lab/habitat/tasks/rearrange/rearrange_sensors.py
    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    SENSORS: ["TARGET_START_SENSOR", "JOINT_SENSOR"]

    # Measurements
    # 定义在habitat-lab/habitat/tasks/rearrange/rearrange_sensors.py
    ROBOT_FORCE:
        TYPE: "RobotForce"
        MIN_FORCE: 20.0
    # 定义在habitat-lab/habitat/tasks/rearrange/rearrange_sensors.py
    FORCE_TERMINATE:
        TYPE: "ForceTerminate"
        # Maximum amount of allowed force in Newtons.
        MAX_ACCUM_FORCE: 5000.0
    # 上文已定义
    DISTANCE_TO_TARGET_OBJECT:
        TYPE: "DistanceToTargetObject"
    # 上文已定义
    NAV_PICK_REWARD:
        TYPE: "NavPickReward"
        SCALING_FACTOR: 0.1

        # General Rearrange Reward config
        # 普遍的Rearrange奖励设置
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.001
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0

    # 上文已定义
    NAV_PICK_SUCCESS:
        TYPE: "NavPickSuccess"

    # 衡量指标
    MEASUREMENTS:
        # The measurements returned in the info dictionary
        - "ROBOT_FORCE"
        - "FORCE_TERMINATE"
        - "DISTANCE_TO_TARGET_OBJECT"
        - "NAV_PICK_REWARD"
        - "NAV_PICK_SUCCESS"
    # 动作
    ACTIONS:
        # Define the action space.
        # 继承自habitat-lab/habitat/tasks/rearrange/actions.py
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
        # 继承自habitat-lab/habitat/tasks/rearrange/actions.py
        BASE_VELOCITY:
            TYPE: "BaseVelAction"
            LIN_SPEED: 12.0
            ANG_SPEED: 12.0
            ALLOW_DYN_SLIDE: True
            END_ON_STOP: False
            ALLOW_BACK: True
            MIN_ABS_LIN_SPEED: 1.0
            MIN_ABS_ANG_SPEED: 1.0
    POSSIBLE_ACTIONS:
        - ARM_ACTION
        - BASE_VELOCITY

# 定义模拟器参数
SIMULATOR:
    DEBUG_RENDER: False
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    CONCUR_RENDER: False
    AUTO_SLEEP: False
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: False
        RADIUS: 0.1
        SENSORS: ['HEAD_RGB_SENSOR']
        START_POSITION: [0, 0, 0]
        START_ROTATION: [0, 0, 0, 1]
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 4
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobot"
    FORWARD_STEP_SIZE: 0.25

    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0

    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    TYPE: RearrangeSim-v0