__BASE__: "{fileDirname}/base.yaml"

SOLUTION:
  PickAndPlace:
    PickRLSkill:
      TYPE: PickRLSkill
      ACTION: BaseArmGripperAction2
      CKPT_PATH: "data/results/rearrange/skills/tidy_house/pick_v1_joint_SCR/seed=100/checkpoints/ckpt.10.pth"
      TIMEOUT: 200
      END_TYPE: "obs"
      THRESHOLD: 0.05

    PlaceRLSkill:
      TYPE: PlaceRLSkill
      ACTION: BaseArmGripperAction2
      CKPT_PATH: "data/results/rearrange/skills/tidy_house/place_v1_joint_SCR/seed=100/checkpoints/ckpt.10.pth"
      TIMEOUT: 200
      END_TYPE: "obs"
      THRESHOLD: 0.05

    NavRLSkill:
      TYPE: NavRLSkill
      ACTION: BaseDiscVelAction
#      CKPT_PATH: "data/results/rearrange/skills/tidy_house/nav_v1_disc_SCR/seed=100/checkpoints/ckpt.10.pth"
#      CKPT_PATH: "/home/lu/Desktop/embodied_ai/data/results/rearrange/skills/tidy_house/checkpoints/nav_v2/ckpt_pre.pth"
      CKPT_PATH: "/home/lu/Desktop/embodied_ai/data/results/rearrange/skills/tidy_house/checkpoints/nav_v3/ckpt.-1.pth"
      TIMEOUT: 500
      END_TYPE: "call_stop"
