__BASE__: "{fileDirname}/nav_v0_disc_SCR.yaml"
BASE_TASK_CONFIG_PATH: "configs/rearrange/tasks/nav_v1.yaml"

RL:
  # 定义RL的采用的奖励函数
  REWARD_MEASURES:
    - "rearrange_nav_reward"
    - "force_penalty"
